"""0001_baseline

Revision ID: 0001
Revises: 
Create Date: 2026-05-14 21:29:56.148182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('tehsil', sa.String(length=80), nullable=True),
    sa.Column('assigned_villages', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_workers_district'), 'extension_workers', ['district'], unique=False)
    op.create_index(op.f('ix_extension_workers_phone'), 'extension_workers', ['phone'], unique=True)
    op.create_table('farmers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('tehsil', sa.String(length=80), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_district'), 'farmers', ['district'], unique=False)
    op.create_index(op.f('ix_farmers_phone'), 'farmers', ['phone'], unique=True)
    op.create_table('memory_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scale', sa.String(length=20), nullable=False),
    sa.Column('scale_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('key_patterns', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('atom_count', sa.Integer(), nullable=True),
    sa.Column('farmer_count', sa.Integer(), nullable=True),
    sa.Column('field_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('min_farmers_required', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_summaries_scale'), 'memory_summaries', ['scale'], unique=False)
    op.create_index(op.f('ix_memory_summaries_scale_id'), 'memory_summaries', ['scale_id'], unique=False)
    op.create_index('ix_memory_summaries_scale_lookup', 'memory_summaries', ['scale', 'scale_id'], unique=False)
    op.create_table('wiki_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_hi', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hi', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_hi', sa.Text(), nullable=True),
    sa.Column('applicable_crops', sa.JSON(), nullable=True),
    sa.Column('applicable_stages', sa.JSON(), nullable=True),
    sa.Column('topic_tags', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=30), nullable=True),
    sa.Column('causes_of', sa.JSON(), nullable=True),
    sa.Column('prevented_by', sa.JSON(), nullable=True),
    sa.Column('correlated_with', sa.JSON(), nullable=True),
    sa.Column('followed_by', sa.JSON(), nullable=True),
    sa.Column('treated_by', sa.JSON(), nullable=True),
    sa.Column('aggravated_by', sa.JSON(), nullable=True),
    sa.Column('variant_of', sa.JSON(), nullable=True),
    sa.Column('regional_of', sa.JSON(), nullable=True),
    sa.Column('confused_with', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=300), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('tehsil', sa.String(length=80), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('crop_name', sa.String(length=60), nullable=True),
    sa.Column('issue_category', sa.String(length=60), nullable=True),
    sa.Column('observation_ids', sa.JSON(), nullable=True),
    sa.Column('advisory_ids', sa.JSON(), nullable=True),
    sa.Column('farmer_count', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('broadcast_message', sa.Text(), nullable=True),
    sa.Column('broadcast_at', sa.DateTime(), nullable=True),
    sa.Column('farmers_notified', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['extension_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_clusters_crop_name'), 'alert_clusters', ['crop_name'], unique=False)
    op.create_index(op.f('ix_alert_clusters_district'), 'alert_clusters', ['district'], unique=False)
    op.create_index(op.f('ix_alert_clusters_tehsil'), 'alert_clusters', ['tehsil'], unique=False)
    op.create_index('ix_clusters_district_crop', 'alert_clusters', ['district', 'crop_name'], unique=False)
    op.create_index('ix_clusters_status', 'alert_clusters', ['status'], unique=False)
    op.create_table('farmer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('farm_size_acres', sa.Float(), nullable=True),
    sa.Column('irrigation_source', sa.String(length=40), nullable=True),
    sa.Column('water_reliability', sa.String(length=20), nullable=True),
    sa.Column('soil_test_status', sa.String(length=30), nullable=True),
    sa.Column('primary_soil_type', sa.String(length=60), nullable=True),
    sa.Column('equipment_access', sa.JSON(), nullable=True),
    sa.Column('labor_availability', sa.String(length=20), nullable=True),
    sa.Column('storage_access', sa.String(length=30), nullable=True),
    sa.Column('transport_access', sa.String(length=30), nullable=True),
    sa.Column('annual_budget_rs', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('credit_access', sa.String(length=30), nullable=True),
    sa.Column('insurance_status', sa.String(length=30), nullable=True),
    sa.Column('organic_preference', sa.Boolean(), nullable=True),
    sa.Column('preferred_mandis', sa.JSON(), nullable=True),
    sa.Column('nearest_mandi_km', sa.Float(), nullable=True),
    sa.Column('pm_kisan_enrolled', sa.Boolean(), nullable=True),
    sa.Column('pmfby_enrolled', sa.Boolean(), nullable=True),
    sa.Column('kcc_holder', sa.Boolean(), nullable=True),
    sa.Column('soil_health_card', sa.Boolean(), nullable=True),
    sa.Column('profile_completeness', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_profiles_farmer_id'), 'farmer_profiles', ['farmer_id'], unique=True)
    op.create_table('fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('area_acres', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=60), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('irrigation_type', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_farmer_id'), 'fields', ['farmer_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('freshness_ttl_hours', sa.Integer(), nullable=True),
    sa.Column('trust_level', sa.String(length=20), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('wiki_article_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['wiki_article_id'], ['wiki_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_source_type'), 'source_documents', ['source_type'], unique=False)
    op.create_table('crop_cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=60), nullable=False),
    sa.Column('variety', sa.String(length=60), nullable=True),
    sa.Column('sowing_date', sa.DateTime(), nullable=True),
    sa.Column('expected_harvest_date', sa.DateTime(), nullable=True),
    sa.Column('current_stage', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cycles_field_id'), 'crop_cycles', ['field_id'], unique=False)
    op.create_table('satellite_ndvi',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ndvi_value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_ndvi_field_id'), 'satellite_ndvi', ['field_id'], unique=False)
    op.create_table('conversation_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=True),
    sa.Column('crop_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('running_summary', sa.Text(), nullable=True),
    sa.Column('last_user_message', sa.Text(), nullable=True),
    sa.Column('last_agent_message', sa.Text(), nullable=True),
    sa.Column('last_advisory_id', sa.String(length=36), nullable=True),
    sa.Column('last_observation_id', sa.String(length=36), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_thread_scope', 'conversation_threads', ['farmer_id', 'field_id', 'crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_conversation_threads_crop_cycle_id'), 'conversation_threads', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_conversation_threads_farmer_id'), 'conversation_threads', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_conversation_threads_field_id'), 'conversation_threads', ['field_id'], unique=False)
    op.create_table('crop_calendar_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('task_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('days_from_sowing', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['crop_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_calendar_tasks_cycle_id'), 'crop_calendar_tasks', ['cycle_id'], unique=False)
    op.create_table('finance_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_entries_farmer_id'), 'finance_entries', ['farmer_id'], unique=False)
    op.create_index('ix_finance_farmer_cycle', 'finance_entries', ['farmer_id', 'crop_cycle_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_cycle_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=True),
    sa.Column('observation_type', sa.String(length=30), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('audio_path', sa.String(length=300), nullable=True),
    sa.Column('vision_analysis', sa.JSON(), nullable=True),
    sa.Column('vision_confidence', sa.Float(), nullable=True),
    sa.Column('reported_stage', sa.String(length=30), nullable=True),
    sa.Column('outcome_text', sa.Text(), nullable=True),
    sa.Column('outcome_rating', sa.Integer(), nullable=True),
    sa.Column('outcome_logged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_crop_cycle_id'), 'observations', ['crop_cycle_id'], unique=False)
    op.create_index('ix_observations_farmer_cycle', 'observations', ['farmer_id', 'crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_observations_farmer_id'), 'observations', ['farmer_id'], unique=False)
    op.create_table('advisories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('selected_action_indices', sa.JSON(), nullable=True),
    sa.Column('selected_warning_indices', sa.JSON(), nullable=True),
    sa.Column('actions_text', sa.JSON(), nullable=True),
    sa.Column('warnings_text', sa.JSON(), nullable=True),
    sa.Column('contextualization', sa.Text(), nullable=True),
    sa.Column('thinking_enabled', sa.Boolean(), nullable=True),
    sa.Column('model_used', sa.String(length=30), nullable=True),
    sa.Column('retrieval_path', sa.String(length=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('evidence_article_ids', sa.JSON(), nullable=True),
    sa.Column('weather_data', sa.JSON(), nullable=True),
    sa.Column('mandi_data', sa.JSON(), nullable=True),
    sa.Column('scheme_data', sa.JSON(), nullable=True),
    sa.Column('memory_reference', sa.Text(), nullable=True),
    sa.Column('previous_observation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('farmer_feedback', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advisories_farmer_created', 'advisories', ['farmer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_advisories_farmer_id'), 'advisories', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_advisories_observation_id'), 'advisories', ['observation_id'], unique=True)
    op.create_table('action_impacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('advisory_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=True),
    sa.Column('crop_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('action_index', sa.Integer(), nullable=True),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('time_horizon', sa.String(length=80), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('metrics_delta', sa.JSON(), nullable=True),
    sa.Column('affects_previous_suggestions', sa.JSON(), nullable=True),
    sa.Column('evidence_article_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_impacts_advisory_action', 'action_impacts', ['advisory_id', 'action_index'], unique=False)
    op.create_index(op.f('ix_action_impacts_advisory_id'), 'action_impacts', ['advisory_id'], unique=False)
    op.create_index(op.f('ix_action_impacts_farmer_id'), 'action_impacts', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_action_impacts_field_id'), 'action_impacts', ['field_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=True),
    sa.Column('crop_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('advisory_id', sa.String(length=36), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('detected_followup', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('retrieval_path', sa.String(length=10), nullable=True),
    sa.Column('evidence_article_ids', sa.JSON(), nullable=True),
    sa.Column('memory_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['conversation_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_farmer_id'), 'conversation_turns', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_field_id'), 'conversation_turns', ['field_id'], unique=False)
    op.create_index('ix_conversation_turns_thread_created', 'conversation_turns', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_turns_thread_id'), 'conversation_turns', ['thread_id'], unique=False)
    op.create_table('source_citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('advisory_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_snapshot', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('citation_context', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_citations_advisory', 'source_citations', ['advisory_id'], unique=False)
    op.create_index(op.f('ix_source_citations_advisory_id'), 'source_citations', ['advisory_id'], unique=False)
    op.create_table('verifier_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('advisory_id', sa.String(length=36), nullable=False),
    sa.Column('passes_all', sa.Boolean(), nullable=True),
    sa.Column('actions_exist_in_wiki', sa.Boolean(), nullable=True),
    sa.Column('warnings_exist_in_wiki', sa.Boolean(), nullable=True),
    sa.Column('indices_in_range', sa.Boolean(), nullable=True),
    sa.Column('actions_match_risk_type', sa.Boolean(), nullable=True),
    sa.Column('actions_dont_contradict_memory', sa.Boolean(), nullable=True),
    sa.Column('passes_regex_filter', sa.Boolean(), nullable=True),
    sa.Column('passes_llm_safety_check', sa.Boolean(), nullable=True),
    sa.Column('confidence_calibrated_to_evidence', sa.Boolean(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifier_reports_advisory_id'), 'verifier_reports', ['advisory_id'], unique=True)
    op.create_table('memory_atoms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=True),
    sa.Column('crop_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('atom_type', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_citation_id', sa.String(length=36), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('tehsil', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['source_citation_id'], ['source_citations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_atoms_atom_type'), 'memory_atoms', ['atom_type'], unique=False)
    op.create_index('ix_memory_atoms_district', 'memory_atoms', ['district', 'atom_type'], unique=False)
    op.create_index(op.f('ix_memory_atoms_event_at'), 'memory_atoms', ['event_at'], unique=False)
    op.create_index('ix_memory_atoms_farmer_event', 'memory_atoms', ['farmer_id', 'event_at'], unique=False)
    op.create_index(op.f('ix_memory_atoms_farmer_id'), 'memory_atoms', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_memory_atoms_field_id'), 'memory_atoms', ['field_id'], unique=False)
    op.create_index('ix_memory_atoms_field_type', 'memory_atoms', ['field_id', 'atom_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_atoms_field_type', table_name='memory_atoms')
    op.drop_index(op.f('ix_memory_atoms_field_id'), table_name='memory_atoms')
    op.drop_index(op.f('ix_memory_atoms_farmer_id'), table_name='memory_atoms')
    op.drop_index('ix_memory_atoms_farmer_event', table_name='memory_atoms')
    op.drop_index(op.f('ix_memory_atoms_event_at'), table_name='memory_atoms')
    op.drop_index('ix_memory_atoms_district', table_name='memory_atoms')
    op.drop_index(op.f('ix_memory_atoms_atom_type'), table_name='memory_atoms')
    op.drop_table('memory_atoms')
    op.drop_index(op.f('ix_verifier_reports_advisory_id'), table_name='verifier_reports')
    op.drop_table('verifier_reports')
    op.drop_index(op.f('ix_source_citations_advisory_id'), table_name='source_citations')
    op.drop_index('ix_source_citations_advisory', table_name='source_citations')
    op.drop_table('source_citations')
    op.drop_index(op.f('ix_conversation_turns_thread_id'), table_name='conversation_turns')
    op.drop_index('ix_conversation_turns_thread_created', table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_field_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_farmer_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_action_impacts_field_id'), table_name='action_impacts')
    op.drop_index(op.f('ix_action_impacts_farmer_id'), table_name='action_impacts')
    op.drop_index(op.f('ix_action_impacts_advisory_id'), table_name='action_impacts')
    op.drop_index('ix_action_impacts_advisory_action', table_name='action_impacts')
    op.drop_table('action_impacts')
    op.drop_index(op.f('ix_advisories_observation_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_farmer_id'), table_name='advisories')
    op.drop_index('ix_advisories_farmer_created', table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_observations_farmer_id'), table_name='observations')
    op.drop_index('ix_observations_farmer_cycle', table_name='observations')
    op.drop_index(op.f('ix_observations_crop_cycle_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_finance_farmer_cycle', table_name='finance_entries')
    op.drop_index(op.f('ix_finance_entries_farmer_id'), table_name='finance_entries')
    op.drop_table('finance_entries')
    op.drop_index(op.f('ix_crop_calendar_tasks_cycle_id'), table_name='crop_calendar_tasks')
    op.drop_table('crop_calendar_tasks')
    op.drop_index(op.f('ix_conversation_threads_field_id'), table_name='conversation_threads')
    op.drop_index(op.f('ix_conversation_threads_farmer_id'), table_name='conversation_threads')
    op.drop_index(op.f('ix_conversation_threads_crop_cycle_id'), table_name='conversation_threads')
    op.drop_index('ix_conversation_thread_scope', table_name='conversation_threads')
    op.drop_table('conversation_threads')
    op.drop_index(op.f('ix_satellite_ndvi_field_id'), table_name='satellite_ndvi')
    op.drop_table('satellite_ndvi')
    op.drop_index(op.f('ix_crop_cycles_field_id'), table_name='crop_cycles')
    op.drop_table('crop_cycles')
    op.drop_index(op.f('ix_source_documents_source_type'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_fields_farmer_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_farmer_profiles_farmer_id'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_index('ix_clusters_status', table_name='alert_clusters')
    op.drop_index('ix_clusters_district_crop', table_name='alert_clusters')
    op.drop_index(op.f('ix_alert_clusters_tehsil'), table_name='alert_clusters')
    op.drop_index(op.f('ix_alert_clusters_district'), table_name='alert_clusters')
    op.drop_index(op.f('ix_alert_clusters_crop_name'), table_name='alert_clusters')
    op.drop_table('alert_clusters')
    op.drop_table('wiki_articles')
    op.drop_index('ix_memory_summaries_scale_lookup', table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_scale_id'), table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_scale'), table_name='memory_summaries')
    op.drop_table('memory_summaries')
    op.drop_index(op.f('ix_farmers_phone'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_district'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_extension_workers_phone'), table_name='extension_workers')
    op.drop_index(op.f('ix_extension_workers_district'), table_name='extension_workers')
    op.drop_table('extension_workers')
    # ### end Alembic commands ###
