"""
AgriMesh V4.0 — Living Memory + Evidence Models
MemoryAtom: extracted field/farmer events
MemorySummary: coarsened summaries by geographic scale
SourceDocument/SourceCitation: evidence provenance tracking
"""
from __future__ import annotations

import uuid

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from app.database import Base
from app.utils.time import utc_now

# ─── Memory Primitives ────────────────────────────────────────────────

class MemoryAtom(Base):
    """
    Single extracted fact from any farm event.
    Source: observation, advisory, finance, NDVI, weather, market, crop task, outcome.
    """
    __tablename__ = "memory_atoms"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    farmer_id = Column(String(36), ForeignKey("farmers.id", ondelete="CASCADE"), nullable=False, index=True)
    field_id = Column(String(36), ForeignKey("fields.id", ondelete="SET NULL"), nullable=True, index=True)
    crop_cycle_id = Column(String(36), ForeignKey("crop_cycles.id", ondelete="SET NULL"), nullable=True)

    # What happened
    atom_type = Column(String(40), nullable=False, index=True)
    # disease_observed, pest_detected, weather_event, price_recorded,
    # expense_logged, revenue_logged, task_completed, yield_recorded,
    # scheme_enrolled, advisory_given, outcome_reported, ndvi_change,
    # stage_transition, irrigation_event, fertilizer_applied, soil_tested

    summary = Column(Text, nullable=False)            # 1-line fact: "Rice blast detected at vegetative stage"
    details = Column(JSON, default=dict)               # Structured data: {severity, area_affected, ...}
    confidence = Column(Float, default=0.85)

    # Source tracking
    source_type = Column(String(30))  # observation, advisory, weather_tool, mandi_tool, finance, ndvi, manual
    source_id = Column(String(36))    # FK to the source record
    source_citation_id = Column(String(36), ForeignKey("source_citations.id", ondelete="SET NULL"), nullable=True)

    # Location context (denormalized for fast queries)
    village = Column(String(120), nullable=True)
    tehsil = Column(String(80), nullable=True)
    district = Column(String(80), nullable=True)
    state = Column(String(80), default="Bihar")

    # Temporal
    event_at = Column(DateTime, nullable=False, index=True)
    created_at = Column(DateTime, default=utc_now)
    is_private = Column(Boolean, default=True)  # True = only visible at field scale

    # Relationships
    source_citation = relationship(
        "SourceCitation",
        foreign_keys=[source_citation_id],
        back_populates="memory_atoms",
    )


class MemorySummary(Base):
    """
    Coarsened memory summary at a geographic scale.
    Auto-generated by the coarsening job when privacy threshold is met.
    """
    __tablename__ = "memory_summaries"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    scale = Column(String(20), nullable=False, index=True)  # field, village, tehsil, district, state, national
    scale_id = Column(String(120), nullable=False, index=True)  # field_id, village_name, tehsil_name, etc.

    # Summary content
    title = Column(String(200))
    summary_text = Column(Text, nullable=False)
    key_patterns = Column(JSON, default=list)       # ["Recurring rice blast in Aug-Sep", "Rising fertilizer costs"]
    stats = Column(JSON, default=dict)               # {total_observations: 45, avg_yield: 24.5, ...}

    # Aggregation metadata
    atom_count = Column(Integer, default=0)
    farmer_count = Column(Integer, default=0)         # >1 only for village+
    field_count = Column(Integer, default=0)
    confidence = Column(Float, default=0.50)

    # Temporal
    period_start = Column(DateTime, nullable=True)
    period_end = Column(DateTime, nullable=True)
    generated_at = Column(DateTime, default=utc_now)
    last_updated = Column(DateTime, default=utc_now)

    # Privacy
    is_public = Column(Boolean, default=False)
    min_farmers_required = Column(Integer, default=3)  # Privacy threshold


# ─── Evidence & Citations ─────────────────────────────────────────────

class SourceDocument(Base):
    """
    Registered evidence source (wiki article, official portal, tool output, memory).
    Every advisory must cite at least one source.
    """
    __tablename__ = "source_documents"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    source_name = Column(String(200), nullable=False)       # Human-readable name
    source_type = Column(String(40), nullable=False, index=True)
    # wiki_article, official_portal, weather_tool, mandi_tool, scheme_tool,
    # finance_record, memory_atom, ndvi_data, soil_test, icar_advisory,
    # farmer_report, extension_worker

    url = Column(String(500), nullable=True)                # Source URL
    description = Column(Text, nullable=True)
    last_fetched = Column(DateTime, nullable=True)          # When data was last refreshed
    freshness_ttl_hours = Column(Integer, default=24)       # How long data is considered fresh
    trust_level = Column(String(20), default="medium")      # high, medium, low, unverified
    is_official = Column(Boolean, default=False)

    # For wiki: which article
    wiki_article_id = Column(String(36), ForeignKey("wiki_articles.id", ondelete="SET NULL"), nullable=True)

    citations = relationship(
        "SourceCitation",
        back_populates="source_document",
        cascade="all, delete-orphan",
    )


class SourceCitation(Base):
    """
    A specific citation linking an advisory to a source document with evidence snapshot.
    """
    __tablename__ = "source_citations"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    advisory_id = Column(String(36), ForeignKey("advisories.id", ondelete="CASCADE"), nullable=False, index=True)
    source_document_id = Column(String(36), ForeignKey("source_documents.id", ondelete="CASCADE"), nullable=False)

    # What was cited
    evidence_snapshot = Column(Text, nullable=True)         # The specific text/claim being cited
    relevance_score = Column(Float, default=0.8)            # How relevant this source is to the advisory
    citation_context = Column(String(200), nullable=True)   # e.g. "Weather humidity data", "Wiki action #3"

    created_at = Column(DateTime, default=utc_now)

    source_document = relationship("SourceDocument", back_populates="citations")
    memory_atoms = relationship(
        "MemoryAtom",
        foreign_keys="MemoryAtom.source_citation_id",
        back_populates="source_citation",
    )


# ─── Extended Farmer Profile ──────────────────────────────────────────

class FarmerProfile(Base):
    """
    Extended farmer profile beyond basic auth.
    One-to-one with Farmer.
    """
    __tablename__ = "farmer_profiles"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    farmer_id = Column(String(36), ForeignKey("farmers.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)

    # Farm characteristics
    farm_size_acres = Column(Float, nullable=True)
    irrigation_source = Column(String(40), nullable=True)   # canal, borewell, rainfed, drip, pond
    water_reliability = Column(String(20), nullable=True)    # reliable, seasonal, unreliable
    soil_test_status = Column(String(30), nullable=True)     # done_recently, done_old, never, in_progress
    primary_soil_type = Column(String(60), nullable=True)

    # Resources
    equipment_access = Column(JSON, default=list)            # ["tractor", "power_tiller", "manual"]
    labor_availability = Column(String(20), nullable=True)   # family, hired, both, scarce
    storage_access = Column(String(30), nullable=True)       # own_godown, rental, none, cooperative
    transport_access = Column(String(30), nullable=True)     # own_vehicle, hired, public

    # Financial
    annual_budget_rs = Column(Integer, nullable=True)
    risk_tolerance = Column(String(20), nullable=True)       # low, medium, high
    credit_access = Column(String(30), nullable=True)        # kcc, bank_loan, moneylender, none
    insurance_status = Column(String(30), nullable=True)     # pmfby_enrolled, other, none

    # Preferences
    organic_preference = Column(Boolean, default=False)
    preferred_mandis = Column(JSON, default=list)            # ["Munger", "Bhagalpur"]
    nearest_mandi_km = Column(Float, nullable=True)

    # Scheme enrollment
    pm_kisan_enrolled = Column(Boolean, default=False)
    pmfby_enrolled = Column(Boolean, default=False)
    kcc_holder = Column(Boolean, default=False)
    soil_health_card = Column(Boolean, default=False)

    # Metadata
    profile_completeness = Column(Float, default=0.0)        # 0.0 to 1.0
    last_updated = Column(DateTime, default=utc_now)


# ─── Conversation Continuity ──────────────────────────────────────────

class ConversationThread(Base):
    """
    Durable farmer conversation scoped to a field/crop cycle.
    Lets farmers continue from prior context even if Telegram process memory is lost.
    """
    __tablename__ = "conversation_threads"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    farmer_id = Column(String(36), ForeignKey("farmers.id", ondelete="CASCADE"), nullable=False, index=True)
    field_id = Column(String(36), ForeignKey("fields.id", ondelete="SET NULL"), nullable=True, index=True)
    crop_cycle_id = Column(String(36), ForeignKey("crop_cycles.id", ondelete="SET NULL"), nullable=True, index=True)
    channel = Column(String(30), default="telegram")

    title = Column(String(200), nullable=True)
    running_summary = Column(Text, default="")
    last_user_message = Column(Text, default="")
    last_agent_message = Column(Text, default="")
    last_advisory_id = Column(String(36), nullable=True)
    last_observation_id = Column(String(36), nullable=True)
    turn_count = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)

    created_at = Column(DateTime, default=utc_now)
    updated_at = Column(DateTime, default=utc_now)

    turns = relationship(
        "ConversationTurn",
        back_populates="thread",
        lazy="selectin",
        cascade="all, delete-orphan",
    )


class ConversationTurn(Base):
    """One user-agent exchange, retained for short-context recovery and audit."""
    __tablename__ = "conversation_turns"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    thread_id = Column(String(36), ForeignKey("conversation_threads.id", ondelete="CASCADE"), nullable=False, index=True)
    farmer_id = Column(String(36), ForeignKey("farmers.id", ondelete="CASCADE"), nullable=False, index=True)
    field_id = Column(String(36), ForeignKey("fields.id", ondelete="SET NULL"), nullable=True, index=True)
    crop_cycle_id = Column(String(36), ForeignKey("crop_cycles.id", ondelete="SET NULL"), nullable=True)
    observation_id = Column(String(36), ForeignKey("observations.id", ondelete="SET NULL"), nullable=True)
    advisory_id = Column(String(36), ForeignKey("advisories.id", ondelete="SET NULL"), nullable=True)

    user_message = Column(Text, default="")
    agent_response = Column(Text, default="")
    detected_followup = Column(Boolean, default=False)
    risk_level = Column(String(30), nullable=True)
    confidence = Column(String(10), nullable=True)
    retrieval_path = Column(String(10), nullable=True)
    evidence_article_ids = Column(JSON, default=list)
    memory_snapshot = Column(Text, default="")
    created_at = Column(DateTime, default=utc_now)

    thread = relationship("ConversationThread", back_populates="turns")


class ActionImpact(Base):
    """
    Deterministic action impact graph node.
    Describes how an advisory action changes expected crop, cost, risk, and later advice.
    """
    __tablename__ = "action_impacts"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    advisory_id = Column(String(36), ForeignKey("advisories.id", ondelete="CASCADE"), nullable=False, index=True)
    farmer_id = Column(String(36), ForeignKey("farmers.id", ondelete="CASCADE"), nullable=False, index=True)
    field_id = Column(String(36), ForeignKey("fields.id", ondelete="SET NULL"), nullable=True, index=True)
    crop_cycle_id = Column(String(36), ForeignKey("crop_cycles.id", ondelete="SET NULL"), nullable=True)

    action_index = Column(Integer, default=0)
    action_text = Column(Text, nullable=False)
    impact_level = Column(String(20), default="medium")  # low, medium, high, critical
    expected_result = Column(Text, default="")
    time_horizon = Column(String(80), default="")
    dependencies = Column(JSON, default=list)
    risks = Column(JSON, default=list)
    metrics_delta = Column(JSON, default=dict)
    affects_previous_suggestions = Column(JSON, default=list)
    evidence_article_ids = Column(JSON, default=list)
    created_at = Column(DateTime, default=utc_now)


# ─── Indexes ──────────────────────────────────────────────────────────

Index("ix_memory_atoms_farmer_event", MemoryAtom.farmer_id, MemoryAtom.event_at)
Index("ix_memory_atoms_field_type", MemoryAtom.field_id, MemoryAtom.atom_type)
Index("ix_memory_atoms_district", MemoryAtom.district, MemoryAtom.atom_type)
Index("ix_memory_atoms_source", MemoryAtom.source_type, MemoryAtom.source_id)
Index("ix_memory_summaries_scale_lookup", MemorySummary.scale, MemorySummary.scale_id)
Index("ix_memory_summaries_updated", MemorySummary.last_updated)
Index("ix_source_documents_trust_name", SourceDocument.trust_level, SourceDocument.source_name)
Index("ix_source_documents_wiki_article_id", SourceDocument.wiki_article_id)
Index("ix_source_citations_advisory", SourceCitation.advisory_id)
Index("ix_source_citations_source_document_id", SourceCitation.source_document_id)
Index("ix_conversation_thread_scope", ConversationThread.farmer_id, ConversationThread.field_id, ConversationThread.crop_cycle_id)
Index("ix_conversation_threads_farmer_updated", ConversationThread.farmer_id, ConversationThread.updated_at)
Index("ix_conversation_turns_thread_created", ConversationTurn.thread_id, ConversationTurn.created_at)
Index("ix_action_impacts_advisory_action", ActionImpact.advisory_id, ActionImpact.action_index)
Index("ix_action_impacts_created_at", ActionImpact.created_at)
